12-DJANGO/Ejercicio/Django/tema12/peliculas/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('<pk>', views.DirectorView.as_view(), name='detalle_director'),
  path('pelicula/<pk>', views.PeliculaView.as_view(), name='detalle_pelicula'),
]

12-DJANGO/Ejercicio/Django/tema12/tema12/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('', include('peliculas.urls')),
    path('admin/', admin.site.urls),
]

12-DJANGO/catalog/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index')
]

12-DJANGO/miproyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

12-DJANGO/Ejercicio/Django/tema12/peliculas/models.py
from django.db import models

class Director(models.Model):
    nombre = models.CharField(max_length=25)
    apellidos = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    fecha_defuncion = models.DateField(null= True, blank = True)
    biografia = models.TextField()
    imagen = models.URLField()

    def __str__(self):
        return self.nombre + " " + self.apellidos 

class Pelicula(models.Model):
    director = models.ForeignKey('Director', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=25)
    sinopsis = models.TextField()
    duracion = models.PositiveIntegerField()
    imagen = models.URLField()
    anyo = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre

12-DJANGO/catalog/models.py
import uuid
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(
        max_length=64, help_text='Pon el nombre del género')


def __str__(self):
    return self.name


class Book(models.Model):
    title = models.CharField(max_length=32)
    author = models.ForeignKey(
        "Author", on_delete=models.SET_NULL, null=True)
    sumary = models.TextField(
        max_length=100, help_text='Pon aquí de qué va el libro')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='El ISBN de 13 caracteres')
    genre = models.ManyToManyField(Genre)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('book_detail', args=[(str(self.id))])


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='ID único para este libro')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintence'),
        ('o', 'On loan'),
        ('a', 'Availible'),
        ('r', 'Reserver'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Disponibilidad del libro')


class Meta:
    ordering = ['due_back']

    def __str__(self) -> str:
        return '%s (%s)' % (self.id, self.book.title)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_brith = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author_detail', args=[(str(self.id))])

    def __str__(self) -> str:
        return '%s, %s' % (self.last_name, self.first_name)

12-DJANGO/Ejercicio/Django/tema12/peliculas/views.py
from django.views import generic

from .models import Director, Pelicula

class IndexView(generic.ListView):
    template_name = 'peliculas/directores.html'
    model = Director

class DirectorView(generic.DetailView):
    template_name = 'peliculas/director.html'
    model = Director

class PeliculaView(generic.DetailView):
    template_name = 'peliculas/pelicula.html'
    model = Pelicula

12-DJANGO/catalog/views.py
from django.shortcuts import render

from .models import Book, Author, BookInstance, Genre


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_authors = Author.objects.all().count()

    disponibles = BookInstance.objects.filter(status__exact='a')

    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_authors': num_authors,
            'disponibles': disponibles,
            'num_instances': num_instances
        }
    )

12-DJANGO/Ejercicio/Django/tema12/peliculas/templates/peliculas/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'peliculas/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
        <h1>{% block header-title %}Directores{% endblock %}</h1>
    </header>
    <main>{% block content %}{% endblock %}</main>
</body>
</html>

12-DJANGO/Ejercicio/Django/tema12/peliculas/templates/peliculas/director.html
{% extends "peliculas/base.html" %}

{% block title %}Director - {{ director }}{% endblock %}

{% block header-title %}{{ director }}{% endblock %}

{% block content %}
<img class="detalle" src="{{ director.imagen }}" alt="Foto de {{ director }}" ><br>
<p>{{ director.fecha_nacimiento}} - {{director.fecha_defuncion | default_if_none:""}}</p>
<h4>Biografía</h4>
<p>{{ director.biografia | linebreaks }}</p>
<h4>Peliculas</h4>
<table>
    <tr>
    {% for pelicula in director.pelicula_set.all %}
        <td onclick="window.location.href='/pelicula/{{pelicula.id}}'">
            <img src="{{ pelicula.imagen }}" alt="Portada de {{ pelicula }}"><br>
            <span class="nombre_pelicula">{{ pelicula }}</span>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay peliculas aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

12-DJANGO/Ejercicio/Django/tema12/peliculas/templates/peliculas/directores.html
{% extends "peliculas/base.html" %}

{% block title %}Directores{% endblock %}


{% block content %}
<table>
    <tr>
    {% for director in object_list %}
        <td onclick="window.location.href='/{{director.id}}'">
            <img src="{{ director.imagen }}" alt="Foto de {{ director }}"><br>
            <span class="nombre_director">{{ director }}{% if director.fecha_defuncion %}&dagger;{% endif %}</span>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay directores aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

12-DJANGO/Ejercicio/Django/tema12/peliculas/templates/peliculas/pelicula.html
{% extends "peliculas/base.html" %}

{% block title %}Pelicula - {{ pelicula }}{% endblock %}

{% block header-title %}{{ pelicula }}{% endblock %}

{% block content %}
<img class="detalle" src="{{ pelicula.imagen }}"
  alt="Portada de {{ pelicula }}"><br>
<p><b>Año: </b>{{ pelicula.año}}</p>
<h4>Sinopsis</h4>
<p>{{ pelicula.sinopsis | linebreaks }}</p>
{% endblock %}

12-DJANGO/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
    {%load static%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {%block sidebar%}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index.html' %}">Home</a></li>
                <li><a href="">All Books</a></li>
                <li><a href="">All Authors</a></li>
            </ul>
            {% endblock%}
            </div>
            <div class="col-sm-10">
            {%block content%}{%endblock%}
            </div>
        </div>
    </div>
</body>

</html>

12-DJANGO/catalog/templates/index.html
{% extends 'base_generic.html'%}

{% block content%}

<h1>Local Librery Home</h1>
<p>Welcome to <em>LoclaLibrary</em>, a very basic Django website</p>

<h2>Dynamic Content</h2>

<p>The library has the followings record counts:</p>
<ul>
    <li><strong>Books:</strong>{{% num_books %}}</li>
    <li><strong>Copies:</strong>{{%num_instances%}}</li>
    <li><strong>Copies available:</strong>{{%num_instances_availibles%}}</li>
    <li><strong>Authors:</strong>{{%num_authors%}}</li>
</ul>
{% endblock%}